### ISSUE TITLE
initial install issues: updated_by audit column size too small

### ISSUE THREAD

**Issue by feriksen** [OptimalBI/optimal-data-engine-mssql#1]
Just a quick note: the SUSER_NAME() can quickly return usernames larger then 30 characters (as it did for me, thus breaking the install).

its a quick fix though, replacing all updated_by definitions in the ddl for a larger size (or use sysname).

also, installer chokes when trying to rerun the script, as the SBLogin is already created (fix: add a test for existance/drop/ignore?)

**Comment by Loguteva** [comment]
Hi Fridthjof
Thanks for raising an issue. Both bugs, the user name field sizes and SBLogin existence check, are fixed in the new version (5.1).
